intoduce tls_insecure in provider config for skipping tls cert verification
claranet/terraform-provider-zabbix pull request #35
Opened 2022-03-30 08:27 UTC by FalcoSuessgott

2022-04-05 14:06 UTC, xp-1000 requested changes
Hello,

thanks for the PR, I proposed an untested change to keep debugging capability and do not forget to `setClient` in all cases.

2022-04-05 17:21 UTC, FalcoSuessgott commented on zabbix/provider.go
> +		})
True, lol havent really checked `NewTransport()` function in the first place. Used your suggestion

2022-04-05 17:22 UTC, FalcoSuessgott commented
Hi @xp-1000,

tested the provider  with your suggestion with both log_level on `TRACE` and without it. Both works fine. :)

2022-04-20 07:51 UTC, xp-1000 approved these changes
Hello @FalcoSuessgott 

thanks for your tests and sorry for the delay.

I will release a new version soon.

2022-04-20 07:51 UTC, merged